apiVersion: v1
kind: Pod
metadata:
  labels:
    app: k8s-app
  name: k8s-app
spec:
  containers:
  - image: lucasgiaco91/k8s-app
    imagePullPolicy: Always
    name: k8s-app
    ports:
    - containerPort: 5000
      protocol: TCP
    envFrom:
    - configMapRef:
        name: db-info
    - secretRef:
        name: db-credentials
  restartPolicy: Always
